export BASE_IMAGE_NAME ?=

export AWS_ACCESS_KEY_ID ?=
export AWS_SECRET_ACCESS_KEY ?=
export AWS_REGION ?=
export GITHUB_TOKEN ?=

export PULUMI_BACKEND_STATE_BUCKET_NAME ?=
export PULUMI_STACK_NAME ?=
export PULUMI_HOME ?=
export PULUMI_CONFIG_PASSPHRASE ?=
